# Generated by Django 5.2.17 on 2026-09-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='body',
            field=models.TextField(blank=True, help_text='Markdown with {{placeholder}} variables (client_name, plan_name, ...).'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='deal_type',
            field=models.CharField(choices=[('saas_subscription', 'SaaS monthly/annual fee'), ('fixed_with_ownership', 'Fixed price with code ownership'), ('fixed_hosted', 'Fixed price without ownership, hosting provided')], default='saas_subscription', max_length=32),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Human-reviewed and cleared for rendering real contracts.'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='reference',
            field=models.CharField(blank=True, help_text='External template reference (e.g. e-signature provider template ID).', max_length=255),
        ),
    ]
