# Generated by Django 5.2.17 on 2026-09-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contracttemplate_body_contracttemplate_deal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_document',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_ip',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='signer_document_id',
            field=models.CharField(blank=True, help_text="Signer's CI/RUC.", max_length=32),
        ),
        migrations.AddField(
            model_name='contract',
            name='signer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
