/**
 * Domain types reconciled against the real payments service OpenAPI schema.
 *
 * Generated by exporting `/api/schema` from `payments/` (main tip, commit
 * 483aa3e) via `manage.py spectacular` and reading the source serializers
 * for the two APIView endpoints drf-spectacular cannot introspect
 * (`SignupView`, `PaymentInitiationView`).
 */

export type ContractStatus =
  | "draft"
  | "generated"
  | "sent"
  | "signed"
  | "declined"
  | "voided"
  | "terminated";

/** Transitions a consuming app is allowed to report itself via `POST /contracts/{id}/transition`. */
export type ContractAppReportedStatus = "sent" | "signed";

export type SubscriptionStatus = "trialing" | "active" | "past_due" | "canceled";

export type PaymentStatus = "pending" | "confirmed" | "failed" | "expired";

/** Envelope returned by every paginated list endpoint. */
export interface PaginatedResponse<T> {
  count: number;
  next: string | null;
  previous: string | null;
  results: T[];
}

export interface ContractSummary {
  id: number;
  status: ContractStatus;
  external_envelope_id: string;
  created_at: string;
  signed_at: string | null;
}

export interface SubscriptionSummary {
  id: number;
  status: SubscriptionStatus;
  trial_start: string | null;
  trial_end: string | null;
  current_period_end: string | null;
}

export interface Customer {
  external_ref: string;
  email: string;
  display_name: string;
  created_at: string;
  contract: ContractSummary | null;
  subscription: SubscriptionSummary | null;
}

export interface SignupRequest {
  external_ref: string;
  email?: string;
  display_name?: string;
}

export interface Entitlement {
  entitled: boolean;
  status: string;
  trial_end: string | null;
  current_period_end: string | null;
}

export interface Contract {
  id: number;
  customer: number;
  template: number;
  status: ContractStatus;
  external_envelope_id: string;
  created_at: string;
  updated_at: string;
  signed_at: string | null;
}

export interface ContractTransitionRequest {
  status: ContractAppReportedStatus;
}

export interface Subscription {
  id: number;
  customer: number;
  plan: number;
  status: SubscriptionStatus;
  trial_start: string | null;
  trial_end: string | null;
  current_period_end: string | null;
  canceled_at: string | null;
  created_at: string;
}

export interface Payment {
  id: number;
  subscription: number;
  amount_pyg: number;
  status: PaymentStatus;
  gateway: string;
  gateway_order_id: string;
  checkout_url: string;
  created_at: string;
  updated_at: string;
  confirmed_at: string | null;
}

export interface PaymentInitiationRequest {
  subscription: number;
}

/**
 * Consuming-app / API-key CRUD has no REST endpoints by design — it is
 * managed via the `issue_api_key` management command and the Django admin.
 * The UI does not model this domain as fetchable API resources; the
 * Apps & Keys screen links out to `/admin/` instead (see AppsKeysPage.tsx).
 */
