# Generated by Django 5.1.4 on 2026-07-17 16:42

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Tax ID"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("negotiating", "Negotiating"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("archived", "Archived"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "body_markdown",
                    martor.models.MartorField(
                        help_text="Markdown. Use ${var} for merge fields (e.g. ${client_name}, ${amount}) and {{Signature;role=Client;type=signature}} for DocuSeal signature fields."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Extra merge values as JSON, e.g. {"amount": "$5,000", "start_date": "2026-08-01"}. Referenced in the template as ${amount}, ${start_date}.',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent for signature"),
                            ("viewed", "Viewed"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rendered_html", models.TextField(blank=True, editable=False)),
                ("docuseal_submission_id", models.CharField(blank=True, max_length=64)),
                ("client_signing_url", models.URLField(blank=True)),
                ("owner_signing_url", models.URLField(blank=True)),
                (
                    "signed_pdf_object",
                    models.CharField(
                        blank=True,
                        help_text="MinIO object key of the signed PDF.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="contracts_app.client",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="contracts_app.contracttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
