# Generated by Django 5.2.17 on 2026-09-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_order_id', ''), _negated=True), fields=('gateway', 'gateway_order_id'), name='unique_nonblank_gateway_order_id'),
        ),
    ]
