# Generated by Django 5.2.17 on 2026-09-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_unique_nonblank_gateway_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.TextField(blank=True),
        ),
    ]
