# Generated by Django 5.2.17 on 2026-09-16 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_registry', '0001_initial'),
        ('contracts', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumingapp',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consuming_apps', to='contracts.contracttemplate'),
        ),
        migrations.AddField(
            model_name='consumingapp',
            name='default_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consuming_apps', to='subscriptions.plan'),
        ),
        migrations.AddField(
            model_name='consumingapp',
            name='trial_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
