services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address :9001
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.ignitesolutions.click`)
      - traefik.http.routers.minio.tls.certresolver=myresolver
      - traefik.http.routers.minio.service=minio-api
      - traefik.http.services.minio-api.loadbalancer.server.port=9000
      - traefik.http.routers.minio-console.rule=Host(`minio-console.ignitesolutions.click`)
      - traefik.http.routers.minio-console.tls.certresolver=myresolver
      - traefik.http.routers.minio-console.service=minio-console
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
    networks:
      - traefik_web

volumes:
  minio_data:

networks:
  traefik_web:
    external: true
